# 是否以守护进程方式运行，fork should be used with logpath
fork = true

# 数据库文件位置，需要先创建这个目录
dbpath=/var/lib/mongodb
logpath=/var/log/mongodb/mongodb.log

# 是否以安全认证方式运行，默认是不认证的非安全方式
# auth = true

# 默认27017
port = 27027
