export default {
  height: 1,
  width: 1,
  padding: 1,
  margin: 1,
  top: 1,
  bottom: 1,
  left: 1,
  right: 1,
  alignLeftMargin: 1,
  alignRightMargin: 1,
  alignTopMargin: 1,
  alignBottomMargin: 1,
  minHeight: 1,
  borderWidth: 1,
  borderRadius: 1,
  shadowX: 1,
  shadowY: 1,
  shadowSpread: 1,
  lineHeight: 1,
  fontSize: 1,
};
