import { PAGE_WIDTH, PAGE_HEIGHT } from 'common/constants';
const PROJECTDATA = {
  clazz: 'project',
  userId: '',
  name: '',
  pageTransition: 'none',
  title: '',
  keywords: '',
  description: '',
  preLoadBackgroundImg: '',
  layout: 'normal',
  useData: false,
  usePreloader: false,
  showDisplay: false,
  userSelect: 'auto',
  type: 'h5',
  isUseSensor: 'xeslog',
  sensorBusinessType: 'sensor',
  dynamicLoadScript: true,
  backgroundColor: 'rgba(255, 255, 255, 0)',
  stageWidth: false,
  maxWidth: 500,
  closeImgLazyLoad: false,
  thirdPartyConfig: '',
  origin: '',
  bgImage: '',
  bgSize: 'auto',
  bgSizeScale: 100,
  bgImagePosition: 'center-center',
  bgImageRepeat: 'none',
  runingStartTime: '',
  runingEndTime: '2099-01-01 08:00:00',
  checkLogin: false,
  componentPlat: 'h5',
  miniProgramId: ''
};
const PAGEDATA = {
  clazz: 'page',
  name: '页面',
  pageTitle: '',
  bgColor: '#fff',
  bgImage: '',
  bgSize: 'auto',
  bgSizeScale: 100,
  bgImagePosition: 'center-center',
  bgImageRepeat: 'none',
  isSelected: false,
  width: PAGE_WIDTH,
  heightSetting: 'autoAdjust',
  height: PAGE_HEIGHT,
  isFullPage: false,
  closeImgLazyLoad: false,
};
const WIDGETDATA = {
  clazz: 'widget',
  name: '',
  type: '',
  location: 'page',
  align: 'free',
  alignLeftMargin: 0,
  alignRightMargin: 0,
  alignTopMargin: 0,
  alignBottomMargin: 0,
  required: false,
  width: PAGE_WIDTH,
  height: 200,
  minHeight: 30,
  top: 0,
  left: 0,
  rotate: 0,
  bgColor: 'rgba(255, 255, 255, 0)',
  bgImage: '',
  bgImagePosition: 'center-center',
  bgImageRepeat: 'none',
  bgSize: 'auto',
  bgSizeScale: 100,
  visible: true,
  isSelected: false,
  layout: 'normal',
  pageWidth: 0,
  pageHeight: 0,
  opacity: 100,
  overflowY: 'hidden',
  hasBorderRadius: false,
  borderRadiusPosition: ['TopLeft', 'TopRight', 'BottomLeft', 'BottomRight'],
  borderRadius: 0,
  hasBorder: false,
  borderStyle: 'solid',
  borderWidth: 1,
  borderColor: 'rgba(0, 0, 0, 1)',
  borderDirections: ['top', 'right', 'bottom', 'left'],
  hasShadow: false,
  shadowStyle: 'outset',
  shadowX: 0,
  shadowY: 0,
  shadowBlur: 10,
  shadowSpread: 5,
  shadowColor: 'rgba(0, 0, 0)',
  locked: false,
  readonly: false,
  hasLayers: false,
  defaultLayerCount: 0,
  maxLayerCount: 0,
  padding: '0 0 0 0',
  margin: '0 0 0 0',
  adaptIphoneX: false,
  version: null,
  overflow: 'hidden',
  originName: '',
  isFullPage: false,
};
const LAYERDATA = {
  clazz: 'layer',
  name: '容器',
  heightSetting: 'handAdjust',
  height: 200,
  width: 0,
  isSelected: false,
  isFullPage: false,
  bgColor: 'rgba(255, 255, 255, 0)',
  closeImgLazyLoad: false,
};

export { PROJECTDATA, PAGEDATA, WIDGETDATA, LAYERDATA };
